2014-10-17 15:31:57 ERROR ClientDAO:83 - There is no client with login: CptNipelsdf
2014-10-17 15:31:57 ERROR ClientDAO:139 - Client cannot be null
2014-10-17 15:31:57 ERROR ClientDAO:159 - Client cannot be null
2014-10-17 17:14:30 ERROR BookDAO:69 - There is no book with id: 12
2014-10-20 12:43:14 ERROR ClientDAO:79 - Cannot get client by ID: 
java.sql.SQLException: ORA-03115: неподдерживаемый сетевой тип данных или представление данных

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:813)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1049)
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:854)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1154)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1313)
	at ru.bookstore.DAO.ClientDAO.getClientById(ClientDAO.java:71)
	at ru.bookstore.DAO.ClientDAO.getClientByLogin(ClientDAO.java:91)
	at ru.bookstore.DAO.ClientDAO.main(ClientDAO.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-20 12:43:57 ERROR ClientDAO:79 - Cannot get client by ID: 
java.sql.SQLException: ORA-03115: неподдерживаемый сетевой тип данных или представление данных

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:813)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1049)
	at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:854)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1154)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1313)
	at ru.bookstore.DAO.ClientDAO.getClientById(ClientDAO.java:71)
	at ru.bookstore.DAO.ClientDAO.getClientByLogin(ClientDAO.java:91)
	at ru.bookstore.DAO.ClientDAO.main(ClientDAO.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-20 13:13:10 DEBUG ClientDAO:142 - SQL EXCEPT in changing password

java.sql.SQLException: В индексе отсутствует параметр IN или OUT:: 3
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:1729)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3365)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3454)
	at ru.bookstore.DAO.ClientDAO.changeClientPassword(ClientDAO.java:139)
	at ru.bookstore.DAO.ClientDAO.main(ClientDAO.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-20 13:13:48 DEBUG ClientDAO:142 - SQL EXCEPT in changing password

java.sql.SQLException: В индексе отсутствует параметр IN или OUT:: 3
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:1729)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3365)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3454)
	at ru.bookstore.DAO.ClientDAO.changeClientPassword(ClientDAO.java:139)
	at ru.bookstore.DAO.ClientDAO.main(ClientDAO.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-20 13:16:37 INFO  ClientDAO:140 - Password is changed
2014-10-20 13:18:03 ERROR ClientDAO:145 - Password has not changed. Password incorrect. Invalid access. Try again.
2014-10-20 13:18:03 ERROR ClientDAO:93 - There is no client with login: Paralells lines
2014-10-20 13:18:03 INFO  ClientDAO:119 - Client has been added
2014-10-20 13:51:02 DEBUG BookDAO:96 - There is no book with this name: People are CrazY
2014-10-20 13:51:53 DEBUG BookDAO:129 - This name of Book already exists People are CrazY
2014-10-20 13:53:07 DEBUG BookDAO:96 - There is no book with this name: People are CrazY
2014-10-20 14:44:41 ERROR BookMarkDAO:92 - There is no bookMark with id: 99
2014-10-20 14:44:41 ERROR BookMarkDAO:160 - SQL request insert error
java.sql.SQLException: ORA-00942: таблица или представление пользователя не существует

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.BookMarkDAO.addNewMark(BookMarkDAO.java:158)
	at ru.bookstore.DAO.BookMarkDAO.main(BookMarkDAO.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-20 14:47:07 ERROR BookMarkDAO:92 - There is no bookMark with id: 99
2014-10-20 14:50:38 DEBUG BookMarkDAO:162 - Mark already exists with ID: 99
2014-10-21 13:55:42 ERROR HistoryDAO:92 - There is no bookMark with id: 12
2014-10-21 13:57:33 ERROR HistoryDAO:92 - There is no bookMark with id: 12
2014-10-21 14:00:16 ERROR HistoryDAO:93 - There is no bookMark with id: 12
2014-10-21 14:00:52 ERROR HistoryDAO:93 - There is no bookMark with id: 12
2014-10-21 14:00:52 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_CLIENT_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:00:52 ERROR HistoryDAO:93 - There is no bookMark with id: 12
2014-10-21 14:05:14 ERROR HistoryDAO:93 - There is no bookMark with id: 12
2014-10-21 14:07:03 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:07:03 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_CLIENT_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:07:03 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:20:32 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:20:32 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_CLIENT_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:20:32 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:21:17 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:21:17 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_CLIENT_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:21:17 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:22:06 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:22:06 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_BOOK_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:22:06 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:22:27 ERROR HistoryDAO:93 - There is no history with id: -7151213505452006851
2014-10-21 14:22:27 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_BOOK_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:22:27 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:22:47 ERROR HistoryDAO:93 - There is no history with id: 7743371261961922490
2014-10-21 14:22:47 ERROR HistoryDAO:155 - SQL request insert error
java.sql.SQLException: ORA-02291: нарушено ограничение целостности (VADIM.HISTORY_BOOK_ID) - исходный ключ не найден

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:745)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:219)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1190)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3370)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3476)
	at ru.bookstore.DAO.HistoryDAO.addNewHistoryNote(HistoryDAO.java:153)
	at ru.bookstore.DAO.HistoryDAO.main(HistoryDAO.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
2014-10-21 14:22:47 ERROR HistoryDAO:93 - There is no history with id: 12
2014-10-21 14:27:04 ERROR HistoryDAO:93 - There is no history with id: 8256104195716373891
2014-10-21 14:27:49 ERROR HistoryDAO:93 - There is no history with id: 4672701809888116177
2014-10-21 15:24:42 ERROR HistoryDAO:93 - There is no history with id: 6625770874760374970
